# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (5)
# #########################################################################

class ClassificationResponse(BaseModel):
    model_reasoning: typing.Optional[str] = None
    chosen_theme: typing.Optional["Theme"] = None

class ContactInfo(BaseModel):
    email: typing.Optional[str] = None
    phone: typing.Optional[str] = None
    preferred_contact_method: typing.Optional[str] = None
    call_reasons: typing.Optional[typing.List[str]] = None

class FormResponse(BaseModel):
    personal_info: typing.Optional["PersonalInfo"] = None
    contact_info: typing.Optional["ContactInfo"] = None

class PersonalInfo(BaseModel):
    first_name: typing.Optional[str] = None
    last_name: typing.Optional[str] = None
    gender: typing.Optional[str] = None

class Theme(BaseModel):
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
