# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ClassificationResponse": types.ClassificationResponse,
    "stream_types.ClassificationResponse": stream_types.ClassificationResponse,

    "types.ContactInfo": types.ContactInfo,
    "stream_types.ContactInfo": stream_types.ContactInfo,

    "types.FormResponse": types.FormResponse,
    "stream_types.FormResponse": stream_types.FormResponse,

    "types.PersonalInfo": types.PersonalInfo,
    "stream_types.PersonalInfo": stream_types.PersonalInfo,

    "types.Theme": types.Theme,
    "stream_types.Theme": stream_types.Theme,


}